/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import classes.Musica;
import gerenciador.Spotify;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author igorxf
 */
public class FrCadMusicas extends javax.swing.JFrame {
    private Spotify spotify;
    private boolean editando;
    private String tituloAntigo;
            /**
     * Creates new form FrCadMusicas
     */
    public FrCadMusicas() {
        this.spotify = new Spotify();
        this.editando = false;
        this.tituloAntigo = " ";
        
        initComponents();
        this.habilitaCampos(false);
        this.limparCampos();
        
        try {
            spotify.carregarDoArquivo("ListagemMusicas.csv");
            edtListagem.setText(spotify.toString());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrCadMusicas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        penBotoes = new javax.swing.JPanel();
        btnNova = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        penDig = new javax.swing.JPanel();
        lblTitulom = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        lblDuracao = new javax.swing.JLabel();
        edtTitulo = new javax.swing.JTextField();
        edtArtista = new javax.swing.JTextField();
        edtPreco = new javax.swing.JTextField();
        edtDuracao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Músicas");

        btnNova.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo_32x32.png"))); // NOI18N
        btnNova.setText("Novo");
        btnNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaActionPerformed(evt);
            }
        });
        penBotoes.add(btnNova);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit3_32x32.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        penBotoes.add(btnEditar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_32x32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        penBotoes.add(btnCancelar);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del_32x32.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        penBotoes.add(btnExcluir);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save_32x32.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        penBotoes.add(btnSalvar);

        lblTitulom.setText("Titulo:");

        lblArtista.setText("Artista:");

        lblPreco.setText("Preço");

        lblDuracao.setText("Duração");

        edtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTituloActionPerformed(evt);
            }
        });

        edtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtPrecoActionPerformed(evt);
            }
        });

        edtDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDuracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout penDigLayout = new javax.swing.GroupLayout(penDig);
        penDig.setLayout(penDigLayout);
        penDigLayout.setHorizontalGroup(
            penDigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penDigLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(penDigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(penDigLayout.createSequentialGroup()
                        .addComponent(lblTitulom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(edtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(penDigLayout.createSequentialGroup()
                        .addComponent(lblArtista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(edtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        penDigLayout.setVerticalGroup(
            penDigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penDigLayout.createSequentialGroup()
                .addGroup(penDigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(penDigLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(penDigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(penDigLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblTitulom))
                            .addGroup(penDigLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(edtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(penDigLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(edtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(penDigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(penDigLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(penDigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArtista)
                            .addComponent(lblDuracao)))))
        );

        edtListagem.setColumns(20);
        edtListagem.setRows(5);
        jScrollPane1.setViewportView(edtListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(penDig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(penBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penDig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaActionPerformed
        this.limparCampos();
        this.habilitaCampos(true);
        this.editando= false;
    }//GEN-LAST:event_btnNovaActionPerformed

    private void edtDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDuracaoActionPerformed

    private void edtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTituloActionPerformed

    private void edtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtPrecoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.habilitaCampos(false);
        this.editando = false;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Musica m = this.camposPaObj();
        
        if(editando == true){
            this.spotify.atualizarMusica(this.tituloAntigo, m);
        }else
            this.spotify.adicionarMusica(m);
            
         this.limparCampos();
         this.habilitaCampos(false);
         this.editando = false;
         
         String listagem = spotify.toString();
         edtListagem.setText(listagem);
         
        try {
            spotify.salvarNoArquivo("ListagemMusicas.csv");
        } catch (IOException ex) {
            Logger.getLogger(FrCadMusicas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.tituloAntigo = JOptionPane.showInputDialog("Informe o Titulo da Musica: ", " ");
        Musica musicaEditando= this.spotify.buscarMusica(tituloAntigo);
        
        if(musicaEditando != null){
            this.editando = true;
            this.limparCampos();
            this.habilitaCampos(true);
            
            objPaCampos(musicaEditando);
        }else{
            JOptionPane.showMessageDialog(this, "Produto Inexistente");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        this.tituloAntigo = JOptionPane.showInputDialog("Informe o Titulo da Musica: ", " ");
        Musica m = this.spotify.buscarMusica(tituloAntigo);
        
        if(m == null){
            JOptionPane.showMessageDialog(this, "Produto Inexistente");
        }else{
            this.spotify.removerMusica(tituloAntigo);
        }
        
        String listagem = this.spotify.toString();
        edtListagem.setText(listagem);
    }//GEN-LAST:event_btnExcluirActionPerformed
    
    public Musica camposPaObj(){
        Musica m = new Musica();
        m.setTitulo(edtTitulo.getText());
        m.setArtista(edtArtista.getText());
    
         String strPreco = edtPreco.getText();
        if(!strPreco.isEmpty()){
            double preco = Double.parseDouble(strPreco);
            m.setPreco(preco);
        }
        String strDuracao = edtDuracao.getText();
        if(!strDuracao.isEmpty()){
            double duracao = Double.parseDouble(strDuracao);
            m.setDuracao(duracao);
        }
        return m;
    }
    
    public void objPaCampos(Musica m){
         edtTitulo.setText(m.getTitulo());
         edtArtista.setText(m.getArtista());
         edtPreco.setText(m.getPreco() + " ");
         edtDuracao.setText(m.getDuracao() +" ");
    }
    
    public void habilitaCampos(boolean flag){
        this.edtTitulo.setEnabled(flag);
        this.edtArtista.setEnabled(flag);
        this.edtPreco.setEnabled(flag);
        this.edtDuracao.setEnabled(flag);
    }
    
    public void limparCampos(){
         this.edtTitulo.setText("");
        this.edtArtista.setText("");
        this.edtPreco.setText("");
        this.edtDuracao.setText("");
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNova;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtArtista;
    private javax.swing.JTextField edtDuracao;
    private javax.swing.JTextArea edtListagem;
    private javax.swing.JTextField edtPreco;
    private javax.swing.JTextField edtTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblDuracao;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulom;
    private javax.swing.JPanel penBotoes;
    private javax.swing.JPanel penDig;
    // End of variables declaration//GEN-END:variables
}
